# Generated by Django 5.2.5 on 2025-08-13 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='voice/')),
                ('text', models.TextField(blank=True)),
                ('intent', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ORDER', 'Order'), ('DELIVERY_REVIEW', 'Delivery Review'), ('MEAL_REVIEW', 'Meal Review'), ('HEALTHCARE', 'Healthcare')], default='UNKNOWN', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
