# Generated by Django 5.2.5 on 2025-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_audio', models.FileField(upload_to='user_audio/')),
                ('user_text', models.TextField(blank=True)),
                ('ai_text', models.TextField(blank=True)),
                ('ai_audio', models.FileField(blank=True, null=True, upload_to='ai_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
