# Generated by Django 5.2.5 on 2025-08-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], max_length=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_label', models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], max_length=30)),
                ('source', models.CharField(choices=[('BUTTON', '버튼'), ('VOICE', '음성')], default='BUTTON', max_length=6)),
                ('option_label', models.CharField(blank=True, max_length=30)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='mealreview.reviewoption')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOption',
            fields=[
            ],
            options={
                'verbose_name': 'Detail Option',
                'verbose_name_plural': 'Detail Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mealreview.reviewoption',),
        ),
    ]
