# Generated by Django 5.2.5 on 2025-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('GOOD', '칭찬'), ('BAD', '불만')], max_length=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
