# Generated by Django 5.2.5 on 2025-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreview', '0002_detailoption_reviewoption_remove_meallog_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
