# Generated by Django 5.2.5 on 2025-08-21 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreview', '0002_reviewoption'),
        ('orders', '0002_order_delivery_fee_order_menu_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('initial_label', models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], db_index=True, max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['initial_label', 'sort_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='stage',
        ),
        migrations.AddField(
            model_name='meallog',
            name='initial_label',
            field=models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meallog',
            name='option_label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='meallog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='source',
            field=models.CharField(choices=[('BUTTON', '버튼'), ('VOICE', '음성')], default='BUTTON', max_length=6),
        ),
        migrations.AddField(
            model_name='meallog',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meallog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallog',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mealreview.detailoption'),
        ),
    ]
