# Generated by Django 5.2.5 on 2025-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreview', '0003_meallog_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailoption',
            options={'ordering': ['initial_label', 'sort_order', 'id']},
        ),
        migrations.AlterField(
            model_name='meallog',
            name='source',
            field=models.CharField(choices=[('BUTTON', '버튼'), ('VOICE', '음성')], default='BUTTON', max_length=6),
        ),
    ]
