# Generated by Django 5.2.5 on 2025-08-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreview', '0004_alter_detailoption_options_alter_meallog_source'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewOption',
        ),
        migrations.AddField(
            model_name='meallog',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='detailoption',
            name='initial_label',
            field=models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='initial_label',
            field=models.CharField(choices=[('GOOD', '잘 먹었어요'), ('BAD', '별로였어요')], max_length=30),
        ),
    ]
