# Generated by Django 5.2.5 on 2025-08-22 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(help_text='g, mg, µg, ml', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('delivery_fee', models.IntegerField(default=0)),
                ('delivery_time', models.IntegerField(default=0, help_text='분 단위, 근처 식당 주문이므로 1시간이 넘어가는 경우는 제외함..')),
                ('district_name', models.CharField(help_text='표시용 동명(예: 연희동)', max_length=40)),
                ('district_code', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('keyword', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('0', '국 · 찌개'), ('1', '밥'), ('2', '죽'), ('3', '반찬')], default='0', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('price', models.IntegerField(default=0)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='menus', to='restaurants.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='해당 메뉴 1회분의 영양소 함량')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_nutritions', to='restaurants.menu')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_values', to='restaurants.nutrient')),
            ],
            options={
                'unique_together': {('menu', 'nutrient')},
            },
        ),
    ]
