# Generated by Django 5.2.5 on 2025-08-12 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('tag', models.CharField(max_length=100)),
                ('name_initials', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('district_name', models.CharField(help_text='표시용 동명(예: 연희동)', max_length=40)),
                ('district_code', models.CharField(db_index=True, help_text='행정/법정동 10자리 코드(예: 1141061500)', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', '행정/법정동 코드는 10자리 숫자여야 합니다.')])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='language',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_initials',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='menus', to='restaurants.ingredient'),
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='restaurants.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='menus', to='restaurants.tag'),
        ),
    ]
