# Generated by Django 5.2.5 on 2025-08-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menu_price'),
        ('voice', '0002_alter_transcription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_transcription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voice.transcription')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientAlias',
        ),
    ]
