# Generated by Django 5.2.5 on 2025-08-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_delivery_fee_searchlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='source_transcription',
        ),
        migrations.AddField(
            model_name='searchlog',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
