# Generated by Django 5.2.5 on 2025-08-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menu_price_restaurant_delivery_fee_searchlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(help_text='g, mg, kcal 등', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='해당 메뉴 1회분의 영양소 함량')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_nutritions', to='restaurants.menu')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_values', to='restaurants.nutrient')),
            ],
            options={
                'unique_together': {('menu', 'nutrient')},
            },
        ),
    ]
