# Generated by Django 5.2.5 on 2025-08-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_searchlog_source_transcription_searchlog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(help_text='g, mg, µg, ml', max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name_initials',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_initials',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[(0, '국 · 찌개'), (1, '밥'), (2, '죽'), (3, '반찬')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='MenuNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='해당 메뉴 1회분의 영양소 함량')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_nutritions', to='restaurants.menu')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_values', to='restaurants.nutrient')),
            ],
            options={
                'unique_together': {('menu', 'nutrient')},
            },
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
