# Generated by Django 5.2.5 on 2025-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_nutrient_menunutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name_initials',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_initials',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tag',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[(0, '국 · 찌개'), (1, '밥'), (2, '죽'), (3, '반찬')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(help_text='g, mg, µg, ml', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='district_code',
            field=models.CharField(max_length=10),
        ),
    ]
