# Generated by Django 5.2.5 on 2025-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_menu_name_initials_remove_menu_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(default=0),
        ),
    ]
