# Generated by Django 5.2.5 on 2025-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_nutrient_remove_menu_tags_remove_menu_name_initials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='district_code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
