# Generated by Django 5.2.5 on 2025-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(default=0, help_text='분 단위, 근처 식당 주문이므로 1시간이 넘어가는 경우는 제외함..'),
        ),
    ]
