# Generated by Django 5.2.5 on 2025-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('0', '국 · 찌개'), ('1', '밥'), ('2', '죽'), ('3', '반찬')], default='0', max_length=10),
        ),
    ]
