# Generated by Django 5.2.5 on 2025-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon',
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='사용자가 보유한 질환', related_name='users', to='healthcare.disease'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
