# Generated by Django 5.2.5 on 2025-08-13 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', '6자리 숫자를 입력하세요.')]),
        ),
    ]
