# Generated by Django 5.2.5 on 2025-08-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
