# Generated by Django 5.2.5 on 2025-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='보호자 이메일'),
        ),
    ]
