# Generated by Django 5.2.5 on 2025-08-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_order'),
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='사용자가 보유한 질환', related_name='users', to='healthcare.disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='district_name',
            field=models.CharField(blank=True, help_text='표시용 동명(예: 연희동)', max_length=40, null=True),
        ),
    ]
