# Generated by Django 5.2.5 on 2025-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_fee_remove_order_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_request',
            field=models.CharField(blank=True, choices=[('call', '도착하면 전화해주세요.'), ('text', '도착하면 문자해주세요.'), ('in_person', '직접 받을게요. (부재시 문 앞)'), ('bell', '문 앞에 놔주세요. (초인종 O)'), ('no_bell', '문 앞에 놔주세요. (초인종 X)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '만나서 현금결제'), ('card', '만나서 카드결제')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_request',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
