# Generated by Django 5.2.5 on 2025-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_coupon_user_diseases_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='user',
            name='district_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='district_name',
            field=models.CharField(default=1, help_text='표시용 동명(예: 연희동)', max_length=40),
            preserve_default=False,
        ),
    ]
