# Generated by Django 5.2.5 on 2025-08-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_label', models.CharField(choices=[('GOOD', '아무 문제 없어요'), ('BAD', '어딘가 불편해요')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('mood_label', models.CharField(blank=True, choices=[('GREAT', '최고예요!'), ('FINE', '괜찮아요'), ('SOSO', '그냥 그래요'), ('BAD', '안 좋아요'), ('TERRIBLE', '나빠요')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_once', models.FloatField(blank=True, help_text='1회 제공 최소 섭취량 (mg 단위)', null=True)),
                ('max_once', models.FloatField(blank=True, help_text='1회 제공 최대 섭취량 (mg 단위)', null=True)),
                ('percent_min', models.FloatField(blank=True, help_text='열량 대비 최소 비율 (%)', null=True)),
                ('percent_max', models.FloatField(blank=True, help_text='열량 대비 최대 비율 (%)', null=True)),
                ('use_per_1000kcal', models.BooleanField(default=False)),
                ('per_1000kcal_min', models.FloatField(blank=True, help_text='1000kcal 당 최소 (mg 단위)', null=True)),
                ('per_1000kcal_max', models.FloatField(blank=True, help_text='1000kcal 당 최대 (mg 단위)', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_rules', to='healthcare.disease')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_rules', to='restaurants.nutrient')),
            ],
            options={
                'unique_together': {('disease', 'nutrient')},
            },
        ),
        migrations.CreateModel(
            name='NutritionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_disease', to='healthcare.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_diseases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'disease')},
            },
        ),
    ]
