<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-21 03:05

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.5 on 2025-08-16 20:53

import django.db.models.deletion
>>>>>>> origin/backup_0821
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('restaurants', '0004_nutrient_menunutrition'),
>>>>>>> origin/backup_0821
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='HealthcareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_label', models.CharField(choices=[('GOOD', '아무 문제 없어요'), ('BAD', '어딘가 불편해요')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('mood_label', models.CharField(blank=True, choices=[('GREAT', '최고예요!'), ('FINE', '괜찮아요'), ('SOSO', '그냥 그래요'), ('BAD', '안 좋아요'), ('TERRIBLE', '나빠요')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_logs', to=settings.AUTH_USER_MODEL)),
            ],
=======
            name='DiseaseRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_week', models.FloatField(blank=True, null=True)),
                ('max_week', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_rules', to='healthcare.disease')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_rules', to='restaurants.nutrient')),
            ],
            options={
                'unique_together': {('disease', 'nutrient')},
            },
>>>>>>> origin/backup_0821
        ),
    ]
