# Generated by Django 5.2.5 on 2025-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserules',
            name='percent_max',
            field=models.FloatField(blank=True, help_text='열량 대비 최대 비율 (%)', null=True),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='percent_min',
            field=models.FloatField(blank=True, help_text='열량 대비 최소 비율 (%)', null=True),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='rule_type',
            field=models.CharField(choices=[('ABSOLUTE', '절대값'), ('PERCENT', '비율')], default='ABSOLUTE', max_length=10),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='use_per_1000kcal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diseaserules',
            name='max_week',
            field=models.FloatField(blank=True, help_text='주당 최대 섭취량 (mg 단위)', null=True),
        ),
        migrations.AlterField(
            model_name='diseaserules',
            name='min_week',
            field=models.FloatField(blank=True, help_text='주당 최소 섭취량 (mg 단위)', null=True),
        ),
    ]
