# Generated by Django 5.2.5 on 2025-08-21 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_diseaserules_percent_max_diseaserules_percent_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaserules',
            name='max_week',
        ),
        migrations.RemoveField(
            model_name='diseaserules',
            name='min_week',
        ),
        migrations.RemoveField(
            model_name='diseaserules',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='max_once',
            field=models.FloatField(blank=True, help_text='1회 제공 최대 섭취량 (mg 단위)', null=True),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='min_once',
            field=models.FloatField(blank=True, help_text='1회 제공 최소 섭취량 (mg 단위)', null=True),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='per_1000kcal_max',
            field=models.FloatField(blank=True, help_text='1000kcal 당 최대 (mg 단위)', null=True),
        ),
        migrations.AddField(
            model_name='diseaserules',
            name='per_1000kcal_min',
            field=models.FloatField(blank=True, help_text='1000kcal 당 최소 (mg 단위)', null=True),
        ),
        migrations.CreateModel(
            name='NutritionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_disease', to='healthcare.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_diseases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'disease')},
            },
        ),
    ]
