# Generated by Django 5.2.5 on 2025-08-21 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
                ('initial_label', models.CharField(choices=[('GOOD', '네'), ('BAD', '별로였어요')], db_index=True, max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['initial_label', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_label', models.CharField(choices=[('GOOD', '네'), ('BAD', '별로였어요')], max_length=20)),
                ('source', models.CharField(choices=[('BUTTON', '버튼'), ('VOICE', '음성')], default='BUTTON', max_length=6)),
                ('option_label', models.CharField(blank=True, max_length=30)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveryreview.detailoption')),
            ],
        ),
    ]
