# Generated by Django 5.2.5 on 2025-08-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryreview', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailoption',
            name='initial_label',
            field=models.CharField(choices=[('GOOD', '네'), ('BAD', '별로였어요')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='initial_label',
            field=models.CharField(choices=[('GOOD', '네'), ('BAD', '별로였어요')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
    ]
