# Generated by Django 5.2.5 on 2025-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryreview', '0002_alter_detailoption_initial_label_deliverylog_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailoption',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
